query Characters {
  allPeople {
    people {
      name
      birthYear
      id
    }
  }
}

query getPerson($personId: ID) {
  person(id: $personId) {
    id
    name
    gender
    hairColor
    mass
    skinColor
    birthYear
    species {
      name
    }
    starshipConnection {
      starships {
        name
      }
    }
    vehicleConnection {
      vehicles {
        name
      }
    }
    filmConnection {
      films {
        id
        title
        director
        episodeID
        openingCrawl
        planetConnection {
          planets {
            name
          }
        }
        producers
        releaseDate
      }
    }
    homeworld {
      name
    }
  }
}
